#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EasySDK.Mobile.Android.Resource", IsApplication=false)]

namespace EasySDK.Mobile.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public static int circle_check_white_18 = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int error_white_18 = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int fail_stamp_picture = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int ic_account_dark_24px = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int ic_add_photo_white_24px = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int ic_add_white_24px = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int ic_back_white_24px = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int ic_big_photo_white_24px = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int ic_cancel_white_24px = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int ic_clear_all_white_24px = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public static int ic_close_white_24px = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public static int ic_copy_all_white_24px = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public static int ic_dark_mode_24px = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public static int ic_delete_white_24px = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public static int ic_key_white_24px = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public static int ic_light_mode_24px = 2130771983;
			
			// aapt resource value: 0x7F010010
			public static int ic_logs_dark_24px = 2130771984;
			
			// aapt resource value: 0x7F010011
			public static int ic_share_white_24px = 2130771985;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F020000
			public static int app_name = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int hello = 2130837505;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F030000
			public static int AlertDarkDialog = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int AlertLightDialog = 2130903041;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
